{
 "title": "All Node Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last Block Transactions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "*.LastBlockTxs" }
   ]
  },
  {
   "title": "Current Block Height",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "target": "*.Height" }
   ]
  },
  {
   "title": "Current Wallet Balances",
   "type": "bargauge",
   "description": "Wallet balances in AR",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "target": "*.WalletBalance" }
   ]
  },
  {
   "title": "Network Hash per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Hs", "label": "Network Hash" }
   ],
   "targets": [
    {
     "target": "arweave-3.Network_hash_per_second"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "description": "Network difficulty",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "arweave-3.Difficulty" }
   ]
  },
  {
   "title": "Last Reported Hash",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "*.Metrics.miner_hashes_per_second"
    }
   ]
  },
  {
   "title": "Errors Found This Session",
   "type": "graph",
   "description": "Any error found this session.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "target": "*.Logs.Errors.error_report_count"
    }
   ]
  },
  {
   "title": "Current Peers",
   "type": "graph",
   "description": "Peers found for each node.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "*.Peers.Total" }
   ]
  },
  {
   "title": "Average Hash per Second",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "target": "*.Metrics.miner_hashes_per_second"
    }
   ]
  },
  {
   "title": "Hashes per Second",
   "type": "graph",
   "description": "Hashes per second across all nodes.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "target": "*.Metrics.miner_hashes_per_second"
    }
   ]
  },
  {
   "title": "Fork Recoveries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Forks.fork_recovered_successfully_count"
    }
   ]
  },
  {
   "title": "Blocks Found This Session",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Blocks" }
   ],
   "targets": [
    { "target": "*.Logs.Blocks_Found" }
   ]
  },
  {
   "title": "Luck (Chance of finding a block)",
   "type": "gauge",
   "description": "This does not take into account network or disk utilization.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "target": "*.Metrics.Luck" }
   ]
  },
  {
   "title": "Current Latency",
   "type": "graph",
   "description": "Latency from all nodes.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "*.Latency" }
   ]
  },
  {
   "title": "Transaction Bytes per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "target": "*.Metrics.tx_bytes_per_second" }
   ]
  }
 ]
}