{
 "title": "All Node Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All Nodes H/S",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "target": "*.Metrics.miner_hashes_per_second"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "target": "arweave-3.Difficulty" }
   ]
  },
  {
   "title": "Last Block Txs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "*.LastBlockTxs" }
   ]
  },
  {
   "title": "Initialize RandomX Hashing",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Info.init_randomx_hashing_count"
    }
   ]
  },
  {
   "title": "Unexpected Tx Response: Connection Refused",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Warning.unexpected_tx_response_econnrefused_count"
    }
   ]
  },
  {
   "title": "No Foreign Blocks Found",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Errors.no_foreign_blocks_found_count"
    }
   ]
  },
  {
   "title": "Unexpected Tx Response: Timeout",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Warning.unexpected_tx_response_timeout_count"
    }
   ]
  },
  {
   "title": "Errors Found",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Errors.error_report_count"
    }
   ]
  },
  {
   "title": "Started Fork Recovery Procedure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Forks.started_fork_recovery_proc_count"
    }
   ]
  },
  {
   "title": "Apply Fork Recovery",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Forks.applying_fork_recovery_count"
    }
   ]
  },
  {
   "title": "Block on Different Fork",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Forks.encountered_block_on_different_fork_to_recovery_process_count"
    }
   ]
  },
  {
   "title": "All Successful Fork Recoveries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Forks.fork_recovered_successfully_count"
    }
   ]
  },
  {
   "title": "Updated Fork Recovery Target",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Forks.updating_fork_recovery_target_count"
    }
   ]
  },
  {
   "title": "Block on Same Fork",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Logs.Forks.encountered_block_on_same_fork_as_recovery_process_count"
    }
   ]
  }
 ]
}