{
 "title": "All Node Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Tx Bytes per Second",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "target": "*.Metrics.tx_bytes_per_second" }
   ]
  },
  {
   "title": "Network H/S",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "target": "arweave-3.Network_hash_per_second"
    }
   ]
  },
  {
   "title": "Average H/S",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "target": "*.Metrics.miner_hashes_per_second"
    }
   ]
  },
  {
   "title": "Last Reported Hash",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "target": "*.Metrics.miner_hashes_per_second"
    }
   ]
  },
  {
   "title": "Total Disk Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Metrics.process_disk_writes_total"
    }
   ]
  },
  {
   "title": "Total Disk Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "*.Metrics.process_disk_reads_total"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    { "target": "*.Metrics.Disk.FreeGB" }
   ]
  },
  {
   "title": "Free RAM",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "targets": [
    { "target": "*.Metrics.RAM.FreeMB" }
   ]
  },
  {
   "title": "IO Page Faults",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "target": "*.Metrics.Process_io_pagefaults_total"
    }
   ]
  },
  {
   "title": "TX Bytes per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "target": "*.Metrics.tx_bytes_per_second" }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "target": "*.Latency" }
   ]
  },
  {
   "title": "Erlang Bytes Output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "*.Metrics.erlang_vm_statistics_bytes_output_total"
    }
   ]
  },
  {
   "title": "Erlang Bytes Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "*.Metrics.erlang_vm_statistics_bytes_received_total"
    }
   ]
  },
  {
   "title": "Erlang VM Memory Processes Total Bytes Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "*.Metrics.Erlang_vm_memory_processes_bytes_total_used"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "*.Metrics.process_open_fds" }
   ]
  }
 ]
}